---
name: Lint
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  lint:
    uses: dceoy/gh-actions-for-devops/.github/workflows/shell-lint.yml@main
    with:
      file-paths: git-rewind-*
